application: imdbvis
version: 1
runtime: php55
api_version: 1
threadsafe: true

handlers:
- url: /js
  static_dir: js

- url: /node_modules
  static_dir: node_modules

- url: /stylesheets
  static_dir: stylesheets

# Serve php scripts.
- url: /(.+\.php)$
  script: \1

- url: /
  script: main.php


