application: imdbvis
version: 1
runtime: php55
api_version: 1
threadsafe: true

handlers:
- url: /js
  static_dir: js

# Serve php scripts.
- url: /(.+\.php)$
  script: \1

- url: /
  script: main.php


